In [1]:
import pandas as pd
print('import ok')

import ok

In [4]:
df = pd.DataFrame()
#initialisation de la data frame

In [5]:
df

Empty DataFrame
Columns: []
Index: []

In [10]:
dic = {'id':[1,2,3,4,5]}
#liste dic avec une clé qui s'appelle id avec des valeur associée 1,2,3,4,5

In [9]:
dic

{'id': [1, 2, 3, 4, 5]}

In [13]:
df = pd.DataFrame(dic)
#on entre notre liste dans le data frame

In [12]:
df

   id
0   1
1   2
2   3
3   4
4   5

In [15]:
df [:2]

   id
0   1
1   2

In [26]:
df = pd.read_csv('chipotle.csv')
#définir variable pour mon data set
#Pour se localisation ./ = le dossier actuel et ../ = le dossier d'avant

In [30]:
pd.read_csv('chipotle.csv')
#afficher le data set

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price
0,0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,1,Izze,[Clementine],$3.39
2,2,1,1,Nantucket Nectar,[Apple],$3.39
3,3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,6,3,1,Side of Chips,NaN,$1.69
7,7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,10,5,1,Chips and Guacamole,NaN,$4.45
11,11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,14,7,1,Chips and Guacamole,NaN,$4.45
15,15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,18,9,2,Canned Soda,[Sprite],$2.18
19,19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,20,10,1,Chips and Guacamole,NaN,$4.45
21,21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,24,12,1,Izze,[Grapefruit],$3.39
25,25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,28,14,1,Canned Soda,[Dr. Pepper],$1.09
29,29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
...,...,...,...,...,...,...
4592,4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$11.75
4593,4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",$11.75
4594,4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",$11.75
4595,4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4596,4596,1826,1,Chips and Guacamole,NaN,$4.45
4597,4597,1826,1,Canned Soft Drink,[Nestea],$1.25
4598,4598,1826,1,Bottled Water,NaN,$1.50
4599,4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
4600,4600,1827,1,Chips and Guacamole,NaN,$4.45
4601,4601,1827,1,Canned Soft Drink,[Diet Coke],$1.25
4602,4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4603,4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4604,4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4605,4605,1828,1,Chips and Guacamole,NaN,$4.45
4606,4606,1828,1,Canned Soft Drink,[Coke],$1.25
4607,4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",$11.75
4608,4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4609,4609,1829,1,Canned Soft Drink,[Sprite],$1.25
4610,4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4611,4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,4613,1831,1,Chips,NaN,$2.15
4614,4614,1831,1,Bottled Water,NaN,$1.50
4615,4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [128]:
df.head()
df[:-1]
#df + [:-1] indique le tableau jusqu'à la dernière ligne
#df + [:5] indique le tableau jusqu'à la 5eme ligne

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price
0,0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,1,Izze,[Clementine],$3.39
2,2,1,1,Nantucket Nectar,[Apple],$3.39
3,3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,6,3,1,Side of Chips,NaN,$1.69
7,7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,10,5,1,Chips and Guacamole,NaN,$4.45
11,11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,14,7,1,Chips and Guacamole,NaN,$4.45
15,15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,18,9,2,Canned Soda,[Sprite],$2.18
19,19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,20,10,1,Chips and Guacamole,NaN,$4.45
21,21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,24,12,1,Izze,[Grapefruit],$3.39
25,25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,28,14,1,Canned Soda,[Dr. Pepper],$1.09
29,29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
...,...,...,...,...,...,...
4591,4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
4592,4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$11.75
4593,4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",$11.75
4594,4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",$11.75
4595,4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4596,4596,1826,1,Chips and Guacamole,NaN,$4.45
4597,4597,1826,1,Canned Soft Drink,[Nestea],$1.25
4598,4598,1826,1,Bottled Water,NaN,$1.50
4599,4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
4600,4600,1827,1,Chips and Guacamole,NaN,$4.45
4601,4601,1827,1,Canned Soft Drink,[Diet Coke],$1.25
4602,4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4603,4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4604,4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4605,4605,1828,1,Chips and Guacamole,NaN,$4.45
4606,4606,1828,1,Canned Soft Drink,[Coke],$1.25
4607,4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",$11.75
4608,4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4609,4609,1829,1,Canned Soft Drink,[Sprite],$1.25
4610,4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4611,4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,4613,1831,1,Chips,NaN,$2.15
4614,4614,1831,1,Bottled Water,NaN,$1.50
4615,4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75

In [29]:
df.describe()

        Unnamed: 0     order_id     quantity
count  4622.000000  4622.000000  4622.000000
mean   2310.500000   927.254868     1.075725
std    1334.400802   528.890796     0.410186
min       0.000000     1.000000     1.000000
25%    1155.250000   477.250000     1.000000
50%    2310.500000   926.000000     1.000000
75%    3465.750000  1393.000000     1.000000
max    4621.000000  1834.000000    15.000000

In [32]:
new_df = df[df['quantity']>1]

In [33]:
new_df.head()

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
18,18,9,2,Canned Soda,[Sprite],$2.18
51,51,23,2,Canned Soda,[Mountain Dew],$2.18
135,135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50
148,148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",$17.98

In [36]:
new_df.describe()

        Unnamed: 0     order_id    quantity
count   267.000000   267.000000  267.000000
mean   2362.314607   947.902622    2.310861
std    1315.357965   521.540732    1.139183
min       4.000000     2.000000    2.000000
25%    1254.500000   511.000000    2.000000
50%    2453.000000   973.000000    2.000000
75%    3598.500000  1443.000000    2.000000
max    4582.000000  1822.000000   15.000000

In [37]:
new_dfBis = df.loc[df['quantity']==2]

In [38]:
#Début exo
df [:10]

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price
0,0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,1,Izze,[Clementine],$3.39
2,2,1,1,Nantucket Nectar,[Apple],$3.39
3,3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,6,3,1,Side of Chips,NaN,$1.69
7,7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [39]:
df.describe()

        Unnamed: 0     order_id     quantity
count  4622.000000  4622.000000  4622.000000
mean   2310.500000   927.254868     1.075725
std    1334.400802   528.890796     0.410186
min       0.000000     1.000000     1.000000
25%    1155.250000   477.250000     1.000000
50%    2310.500000   926.000000     1.000000
75%    3465.750000  1393.000000     1.000000
max    4621.000000  1834.000000    15.000000

In [43]:
df.head()

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price
0,0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,1,Izze,[Clementine],$3.39
2,2,1,1,Nantucket Nectar,[Apple],$3.39
3,3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [129]:
df.groupby("item_name").sum().sort_values(by=['quantity'],ascending=False)[:10]
#obtenir le classement des 10 produit les plus commandés

                              Unnamed: 0  order_id  quantity
item_name
Chicken Bowl                     1779909    713926       761
Chicken Burrito                  1238217    497303       591
Chips and Guacamole              1121773    449959       506
Steak Burrito                     817795    328437       386
Canned Soft Drink                 759990    304753       351
Chips                             518704    208004       230
Steak Bowl                        482721    193752       221
Bottled Water                     439354    175944       211
Chips and Fresh Tomato Salsa      250144    100419       130
Canned Soda                       189915     76396       126

In [120]:
qte_unit = df.quantity

In [121]:
Qte = qte_unit.sum()
#quantité commande

In [150]:
prix_caract = df.item_price.str[1:]
#prendre uniquement la valeur à partir du 2eme caractère
prix = df.item_price.str.replace('$', '').astype('float64')
df['item_price'] = prix
#retirer caractère $ et trasnformer en nombre à virgule

In [144]:
prix

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
5       10.98
6        1.69
7       11.75
8        9.25
9        9.25
10       4.45
11       8.75
12       8.75
13      11.25
14       4.45
15       2.39
16       8.49
17       8.49
18       2.18
19       8.75
20       4.45
21       8.99
22       3.39
23      10.98
24       3.39
25       2.39
26       8.49
27       8.99
28       1.09
29       8.49
        ...
4592    11.75
4593    11.75
4594    11.75
4595     8.75
4596     4.45
4597     1.25
4598     1.50
4599     8.75
4600     4.45
4601     1.25
4602     9.25
4603     9.25
4604     8.75
4605     4.45
4606     1.25
4607    11.75
4608    11.25
4609     1.25
4610    11.75
4611    11.25
4612     9.25
4613     2.15
4614     1.50
4615     8.75
4616     4.45
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [113]:
CA_unit = prix * qte

In [145]:
CA = CA_unit.sum()
#Chiffre d'affaire
#Surcharge d'opérateur = lorsque python reconnait le type d'un objet 
#et qu'il sait lui appliquer la bonne méthode selon l'opérateur qu'on choisit 
#(exemple : + avec 2 strings, va concaténer les chaines de caractères

In [146]:
import numpy as np
#importer variable selon un raccourci et utiliser ce raccouric à chaque fois que l'on veut utiliser cette fonction.
#taper 'np+touche tab du clavier' pour obtenir ensemble des fonctions associées à cette fonction

In [147]:
np.round(CA,1)
#arrondir valeur avec fonction numpy

39237.0

In [148]:
rev_moy = np.round(CA / Qte, 2)

In [126]:
rev_moy

7.89

In [155]:
df["revenue"] = df['quantity'] * df["item_price"]
df.groupby("order_id")['revenue'].sum().mean()
#ajout d'une nouvelle colonne revenue et calcul de la moyenne des revenues du data set

21.394231188658654

In [156]:
df

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price,revenue
0,0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,1,Izze,[Clementine],3.39,3.39
2,2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
5,5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,6,3,1,Side of Chips,NaN,1.69,1.69
7,7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25
10,10,5,1,Chips and Guacamole,NaN,4.45,4.45
11,11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
12,12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75,8.75
13,13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
14,14,7,1,Chips and Guacamole,NaN,4.45,4.45
15,15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
16,16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49,8.49
17,17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49,8.49
18,18,9,2,Canned Soda,[Sprite],2.18,4.36
19,19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75,8.75
20,20,10,1,Chips and Guacamole,NaN,4.45,4.45
21,21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99,8.99
22,22,11,1,Nantucket Nectar,[Pomegranate Cherry],3.39,3.39
23,23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98,10.98
24,24,12,1,Izze,[Grapefruit],3.39,3.39
25,25,13,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
26,26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49,8.49
27,27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99,8.99
28,28,14,1,Canned Soda,[Dr. Pepper],1.09,1.09
29,29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49,8.49
...,...,...,...,...,...,...,...
4592,4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",11.75,11.75
4593,4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75,11.75
4594,4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75,11.75
4595,4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75,8.75
4596,4596,1826,1,Chips and Guacamole,NaN,4.45,4.45
4597,4597,1826,1,Canned Soft Drink,[Nestea],1.25,1.25
4598,4598,1826,1,Bottled Water,NaN,1.50,1.50
4599,4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75,8.75
4600,4600,1827,1,Chips and Guacamole,NaN,4.45,4.45
4601,4601,1827,1,Canned Soft Drink,[Diet Coke],1.25,1.25
4602,4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25,9.25
4603,4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25,9.25
4604,4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75,8.75
4605,4605,1828,1,Chips and Guacamole,NaN,4.45,4.45
4606,4606,1828,1,Canned Soft Drink,[Coke],1.25,1.25
4607,4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75,11.75
4608,4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
4609,4609,1829,1,Canned Soft Drink,[Sprite],1.25,1.25
4610,4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4611,4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25,11.25
4612,4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25,9.25
4613,4613,1831,1,Chips,NaN,2.15,2.15
4614,4614,1831,1,Bottled Water,NaN,1.50,1.50
4615,4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75,8.75
4616,4616,1832,1,Chips and Guacamole,NaN,4.45,4.45
4617,4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75